<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

echo "
<script type='text/javascript'>

	var VALIDATE_ID_MIN_VALUE = ".VALIDATE_ID_MIN_VALUE.";
	var USER_PASSWORD_MIN_SIZE = ".USER_PASSWORD_MIN_SIZE.";
	var USER_PASSWORD_MAX_SIZE = ".USER_PASSWORD_MAX_SIZE.";
	var USER_NAME_MIN_SIZE = ".USER_NAME_MIN_SIZE.";
	var USER_NAME_MAX_SIZE = ".USER_NAME_MAX_SIZE.";
	var USER_NATIONALITY_MAX_SIZE = ".USER_NATIONALITY_MAX_SIZE.";
	var USER_DWELLING_MAX_SIZE = ".USER_DWELLING_MAX_SIZE.";
	var USER_CAR_MAX_SIZE = ".USER_CAR_MAX_SIZE.";
	var USER_SEXUALITY_MAX_SIZE = ".USER_SEXUALITY_MAX_SIZE.";
	var USER_CHILDREN_MAX_SIZE = ".USER_CHILDREN_MAX_SIZE.";
	var USER_PARTNER_MAX_SIZE = ".USER_PARTNER_MAX_SIZE.";
	var USER_OCCUPATION_MAX_SIZE = ".USER_OCCUPATION_MAX_SIZE.";
	var USER_PHONE_MAX_SIZE = ".USER_PHONE_MAX_SIZE.";
	var USER_CONTACT_MESSAGE_MIN_SIZE = ".USER_CONTACT_MESSAGE_MIN_SIZE.";
	var PHOTOS_IN_CARROUSEL = ".PHOTOS_IN_CARROUSEL.";
	var DEFAULT_NO_PHOTO_NAME = '".DEFAULT_NO_PHOTO_NAME."';
	var PROPOSAL_MAX_TO_GET_IN_LISTS = ".PROPOSAL_MAX_TO_GET_IN_LISTS.";
	var PROPOSAL_NAME_MIN_SIZE = ".PROPOSAL_NAME_MIN_SIZE.";
	var PROPOSAL_NAME_MAX_SIZE = ".PROPOSAL_NAME_MAX_SIZE.";
	var PROPOSAL_NAME_MAX_SIZE_WRAP = ".PROPOSAL_NAME_MAX_SIZE_WRAP.";
	var DATATABLES_SHOW_LENGTH = ".DATATABLES_SHOW_LENGTH.";
	var DATATABLES_DEFAULT_LENGHT_MENU = ".DATATABLES_DEFAULT_LENGHT_MENU.";
	var DATATABLES_SHOW_FILTER = ".DATATABLES_SHOW_FILTER.";
	var DATATABLES_SHOW_SORT = ".DATATABLES_SHOW_SORT.";
	var DATATABLES_SHOW_INFO = ".DATATABLES_SHOW_INFO.";
	var DATATABLES_AUTO_WIDTH = ".DATATABLES_AUTO_WIDTH.";
	var DATATABLES_SAVE_COOKIE_STATE = ".DATATABLES_SAVE_COOKIE_STATE.";
	var DATATABLES_PAGINATION_TYPE = '".DATATABLES_PAGINATION_TYPE."';
	var TIME_SECONDS_LEAVE_WRITING_STATUS = ".TIME_SECONDS_LEAVE_WRITING_STATUS.";
	var TIME_SECONDS_ACTUALIZE_MESSAGES_INFO = ".TIME_SECONDS_ACTUALIZE_MESSAGES_INFO.";
	var DEFAULT_NUMBER_USERS_MESSAGED_SHOWED = ".DEFAULT_NUMBER_USERS_MESSAGED_SHOWED.";
	var DEFAULT_NUMBER_MESSAGES_SHOWED = ".DEFAULT_NUMBER_MESSAGES_SHOWED.";
	var TIME_MILISECONDS_ALERTS_HIDE = ".TIME_MILISECONDS_ALERTS_HIDE.";
	var MAIN_PHOTO_WIDTH = ".MAIN_PHOTO_WIDTH.";
	var MAIN_PHOTO_HEIGHT = ".MAIN_PHOTO_HEIGHT.";
	var SUCCESS_AND_FAIL_ANIMATION_CLOSE_SPEED = ".SUCCESS_AND_FAIL_ANIMATION_CLOSE_SPEED.";

	var m_lang = '".DEFAULT_LANGUAGE."';
	var request_url_domain = '".REQUEST_URL_DOMAIN."';
	var request_url_api = '".REQUEST_URL_API."';
	var baseurl = '".BASE_URL."';

	var date_format = new Array();
	date_format['ytod'] = new Array();
	date_format['dtoy'] = new Array();
	date_format['ytod'] = ".LANGUAGES_WITH_DATE_YEAR_TO_DAY.";
	date_format['dtoy'] = ".LANGUAGES_WITH_DATE_DAY_TO_YEAR.";

</script>";

/* End of file constants_js.php */
/* Location: ./js/constants_js.php */